language: node_js
node_js:
  - "0.10"
  - "4.4.3"
sudo: false
services:
  - mongodb
before_install:
  - npm install -g npm@2.13.5
  - npm install -g grunt-cli
  - npm install -g expresso
install: npm install
